Bug 987383 - Make sure to deal with empty output so that JSON stay valid. r=

diff --git a/bin/gaia-perf-marionette b/bin/gaia-perf-marionette
--- a/bin/gaia-perf-marionette
+++ b/bin/gaia-perf-marionette
@@ -61,7 +61,7 @@ for app in $APPS; do
   # wrap marionette-mocha with gaia's defaults. We also need to alter the paths to
   # xpcshell in available for email fake servers.
   export CURRENT_APP="$app"
-  PATH=$XPCSHELL_DIR:$PATH $DIR/../node_modules/.bin/marionette-mocha \
+  OUT=`PATH=$XPCSHELL_DIR:$PATH $DIR/../node_modules/.bin/marionette-mocha \
     --timeout 10s \
     --ui tdd \
     --profile-builder $SHARED/profile_builder.js \
@@ -70,6 +70,13 @@ for app in $APPS; do
     $SHARED/setup.js \
     $GAIA_DIR/tests/performance/perf.js $SHARED_PERF $FILES_PERF \
     -R "$GAIA_DIR/tests/reporters/jsonmozperf.js" \
-    $@ >&3
+    $@`
+  # Bug 987383 if there is no output report an error.
+  if [ -z "$OUT" ]; then
+    echo "$CURRENT_APP returned no output." >&2
+    echo "{ \"stats\": { \"suites\": 1, \"failures\": 1, \"error\": \"No output !\", \"application\": \""$CURRENT_APP"\" } }" >&3
+  else
+    echo "$OUT" >&3
+  fi
 done
 echo ']' >&3
